### ISSUE TITLE
Error timeout

### ISSUE THREAD

**Issue by EnziinSystem** [KamalGalrani/jupyterhub-nativespawner#1]
I passed the authentication step.

```
[D 2020-11-13 12:22:57.255 JupyterHub pages:213] Triggering spawn with default options for username@gmail.com
[D 2020-11-13 12:22:57.256 JupyterHub base:864] Initiating spawn for username@gmail.com
[D 2020-11-13 12:22:57.256 JupyterHub base:868] 0/100 concurrent spawns
[D 2020-11-13 12:22:57.256 JupyterHub base:873] 0 active servers
[D 2020-11-13 12:22:57.294 JupyterHub user:603] Calling Spawner.start for username@gmail.com
[I 2020-11-13 12:22:57.295 JupyterHub spawner:1455] Spawning jupyterhub-singleuser --port=60919 --SingleUserNotebookApp.default_url=/lab '--NotebookApp.tornado_settings={"headers":{"Content-Security-Policy": "frame-ancestors * http://datascience.enziin.com"}}' '--NotebookApp.allow_origin={"*"}'
[D 2020-11-13 12:22:57.318 JupyterHub spawner:1151] Polling subprocess every 30s
[I 2020-11-13 12:22:58.259 JupyterHub log:181] 302 GET /hub/spawn -> /hub/spawn-pending/username@gmail.com (username@gmail.com@58.186.223.92) 1016.90ms
[I 2020-11-13 12:22:58.421 JupyterHub log:181] 200 GET /hub/api (@127.0.0.1) 0.97ms
[I 2020-11-13 12:22:58.481 JupyterHub pages:398] username@gmail.com is pending spawn
[I 2020-11-13 12:22:58.490 JupyterHub log:181] 200 GET /hub/spawn-pending/username@gmail.com (username@gmail.com@58.186.223.92) 15.73ms
[W 2020-11-13 12:23:25.315 JupyterHub user:739] username@gmail.com's server never showed up at http://127.0.0.1:60919/user/username@gmail.com/ after 30 seconds. Giving up
[D 2020-11-13 12:23:25.316 JupyterHub user:791] Stopping username@gmail.com
[D 2020-11-13 12:23:25.328 JupyterHub user:817] Deleting oauth client jupyterhub-user-username%40gmail.com
[D 2020-11-13 12:23:25.338 JupyterHub user:820] Finished stopping username@gmail.com
[E 2020-11-13 12:23:25.347 JupyterHub gen:623] Exception in Future <Task finished name='Task-43' coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /opt/jupyterhub/lib/python3.8/site-packages/jupyterhub/handlers/base.py:884> exception=TimeoutError("Server at http://127.0.0.1:60919/user/username@gmail.com/ didn't respond in 30 seconds")> after timeout
    Traceback (most recent call last):
      File "/opt/jupyterhub/lib/python3.8/site-packages/tornado/gen.py", line 618, in error_callback
        future.result()
      File "/opt/jupyterhub/lib/python3.8/site-packages/jupyterhub/handlers/base.py", line 891, in finish_user_spawn
        await spawn_future
      File "/opt/jupyterhub/lib/python3.8/site-packages/jupyterhub/user.py", line 720, in spawn
        await self._wait_up(spawner)
      File "/opt/jupyterhub/lib/python3.8/site-packages/jupyterhub/user.py", line 767, in _wait_up
        raise e
      File "/opt/jupyterhub/lib/python3.8/site-packages/jupyterhub/user.py", line 734, in _wait_up
        resp = await server.wait_up(
      File "/opt/jupyterhub/lib/python3.8/site-packages/jupyterhub/utils.py", line 231, in wait_for_http_server
        re = await exponential_backoff(
      File "/opt/jupyterhub/lib/python3.8/site-packages/jupyterhub/utils.py", line 179, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://127.0.0.1:60919/user/username@gmail.com/ didn't respond in 30 seconds
    
[
```

**Comment by pbharrin** [comment]
I have the same issue.  This worked fine on my Mac but when I moved to Ubuntu I get the timeout error.  
One thing I noticed was the bash location was different, so I updated that but it did not fix the problem.  

Is there any way we can see what is causing the spawner to hang?

**Comment by pbharrin** [comment]
I fixed this problem with: 
https://github.com/jupyterhub/jupyterhub/issues/1467#issuecomment-334726797

make sue you are running as user ubuntu.
